### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by nicebro123** [zhangzilongc/MMR#5]
跑aebad_v数据集时代码出现路径混乱问题

root@autodl-container-b8cd118952-a284ba93:~/autodl-tmp# sh AeBAD_V_run.sh 
[06/06 10:11:25][INFO] main.py:   26: {'DATASET': {'domain_shift_category': 'same',
             'imagesize': 224,
             'name': 'aebad_V',
             'resize': 256,
             'subdatasets': ['AeBAD_V']},
 'NUM_GPUS': 1,
 'OUTPUT_DIR': './log_MMR_AeBAD_V_54',
 'RNG_SEED': 54,
 'TEST': {'VISUALIZE': CfgNode({'Random_sample': False, 'Sample_num': 40}),
          'dataset_path': './AeBAD',
          'enable': False,
          'method': 'MMR',
          'pixel_mode_verify': False,
          'save_segmentation_images': False,
          'save_video_segmentation_images': True},
 'TEST_SETUPS': CfgNode({'batch_size': 32}),
 'TRAIN': {'MMR': {'DA_low_limit': 0.7,
                   'DA_up_limit': 1.0,
                   'FPN_output_dim': (256, 512, 1024),
                   'feature_compression': False,
                   'finetune_mask_ratio': 0.4,
                   'layers_to_extract_from': ['layer1', 'layer2', 'layer3'],
                   'load_pretrain_model': True,
                   'model_chkpt': './mae_visualize_vit_base.pth',
                   'scale_factors': (4.0, 2.0, 1.0),
                   'test_mask_ratio': 0.0},
           'backbone': 'wideresnet50',
           'dataset_path': './AeBAD',
           'enable': True,
           'method': 'MMR',
           'save_model': False},
 'TRAIN_SETUPS': {'batch_size': 16,
                  'epochs': 200,
                  'learning_rate': 0.001,
                  'num_workers': 1,
                  'warmup_epochs': 50,
                  'weight_decay': 0.05}}
[06/06 10:11:25][INFO] main.py:   27: path_to_config is method_config/AeBAD_V/MMR.yaml
[06/06 10:11:25][INFO] main.py:   31: start training!
[06/06 10:11:25][INFO] train.py:   27: load dataset!
[06/06 10:11:25][INFO] train.py:   55: current individual_dataloader is aebad_V_AeBAD_V.
[06/06 10:11:25][INFO] train.py:   56: the data in current individual_dataloader aebad_V_AeBAD_V are 707.
[06/06 10:11:28][INFO] train.py:   73: train the decoder FPN of MMR from scratch!
[06/06 10:11:28][INFO] train.py:   76: MAE load meg: _IncompatibleKeys(missing_keys=['decoder_FPN_mask_token', 'decoder_FPN_pos_embed', 'simfp_2.0.weight', 'simfp_2.0.bias', 'simfp_2.1.weight', 'simfp_2.1.bias', 'simfp_2.3.weight', 'simfp_2.3.bias', 'simfp_2.4.weight', 'simfp_2.4.norm.weight', 'simfp_2.4.norm.bias', 'simfp_2.5.weight', 'simfp_2.5.norm.weight', 'simfp_2.5.norm.bias', 'simfp_3.0.weight', 'simfp_3.0.bias', 'simfp_3.1.weight', 'simfp_3.1.norm.weight', 'simfp_3.1.norm.bias', 'simfp_3.2.weight', 'simfp_3.2.norm.weight', 'simfp_3.2.norm.bias', 'simfp_4.0.weight', 'simfp_4.0.norm.weight', 'simfp_4.0.norm.bias', 'simfp_4.1.weight', 'simfp_4.1.norm.weight', 'simfp_4.1.norm.bias'], unexpected_keys=[])
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    main()
  File "main.py", line 40, in main
    train(cfg=cfg)
  File "/root/autodl-tmp/tools/train.py", line 99, in train
    MMR_instance.fit(individual_dataloader)
  File "/root/autodl-tmp/models/MMR/MMR_pipeline.py", line 49, in fit
    for image in individual_dataloader:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/datasets/mvtec.py", line 89, in __getitem__
    image = default_loader(image_path)
  File "/root/miniconda3/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 215, in default_loader
    return pil_loader(path)
  File "/root/miniconda3/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 195, in pil_loader
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './AeBAD/AeBAD_V/train/good/./AeBAD/AeBAD_V/train/good/video1_train/28.jpg'
大佬可以帮忙解决一下吗

**Comment by nicebro123** [comment]
已经解决

**Comment by zhangzilongc** [comment]
改成绝对路径就可以了，不过这里还是有点问题，我修复了上传

**Comment by zhangzilongc** [comment]
> 已经解决

改成绝对路径就可以了，不过这里还是有点问题，我修复了上传

**Comment by nicebro123** [comment]
> > 已经解决
> 
> 改成绝对路径就可以了，不过这里还是有点问题，我修复了上传

干的漂亮

**Comment by nicebro123** [comment]
请问大佬 还有关注其他的工业视频异常检测数据集吗？

**Comment by zhangzilongc** [comment]
> 请问大佬 还有关注其他的工业视频异常检测数据集吗？

目前没见过，主要还是以静态的图像为主
